# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - VideoStickerCreator

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          
          
      - name: apt install python3-dev
        run: |
          sudo pip install --upgrade pip
          sudo apt-get update
          sudo apt install python3-all-dev
          sudo apt-get install -y build-essential
          sudo apt-get install python3-dev
          sudo apt-get install -y libpq-dev
          pip3 install psycopg2
          sudo apt-get install python3-dev
          sudo apt install python3-pip
          python3 -m pip install -U pip   
          python3 -m pip install pystan

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: install nes-py
        run: |
          (venv) pip install nes-py
          (venv) pip install Cmake
      
      - name: Install httpstan
        run: (venv) python3 -m pip install httpstan
      
      - name: Install dependencies
        run: (venv) pip install psycopg2-binary
        
      - name: Install More Dependencies
        run: (venv) pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            #!venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: install prerequisites
        run: |
          (venv) sudo apt-get update
          (venv) sudo apt-get install libpython3.11-dev
          (venv) sudo apt install python3-all-dev
          (venv) sudo pip install --upgrade pip
          (venv) sudo apt-get install -y build-essential
          (venv) sudo apt-get install python3-dev
          (venv) sudo apt-get install -y libpq-dev
          (venv) pip3 install psycopg2
          
      - name: apt install python3-dev
        run: |
          (venv) sudo apt-get update
          (venv) sudo apt-get install libpython3.11-dev
          (venv) sudo apt install python3-all-dev
          (venv) sudo apt-get install python3-dev
          #pip install psycopg2-binary
          (venv) sudo pip install --upgrade pip
          (venv) sudo apt-get install -y build-essential
          (venv) sudo apt-get install python3-dev
          (venv) sudo apt-get install -y libpq-dev
          #pip3 install psycopg2
          (venv) sudo apt-get install python3-dev
          (venv) sudo apt install python3-pip
          (venv) python3 -m pip install -U pip   
          (venv) python3 -m pip install pystan
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'VideoStickerCreator'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5361522BBF5648539B15AFDBD4755C13 }}
